### PR TITLE
setup make to setup and run jupyter notebooks

### PR DESCRIPTION
**Pull request by sonalranjit**
- add make target `setup-py` to setup python virtualenv, requirements
- added make target `run-jupyter-notebook` to run Jupyter notebook server
- updated README to reflect the new make targets to use for setting up and running the jupyter notebooks
- cleaned up requirements.txt for the jupyter noteboooks

### CODE REVIEW

**Comment by Arpanio** [comment]
I can test this locally before merging.

Should we agree on a merge policy? 1 dev tests locally before merging?

**Comment by sonalranjit** [comment]
> I can test this locally before merging.
> 
> Should we agree on a merge policy? 1 dev tests locally before merging?

Sure atleast 1 reviewer approving the PR would be fine. i'll lock down the `main` branch once this is in so we can from this point on only get stuff merged in through PRs

**Comment by Arpanio** [comment]
Error running the imports in `RemoveJunkText.ipynb`
>OSError: [E050] Can't find model 'en_core_web_lg'. It doesn't seem to be a Python package or a valid path to a data directory

Error running the imports in `TextExtraction.ipynb`
>ModuleNotFoundError: No module named 'magic'

**Comment by sonalranjit** [comment]
Mm okay i think we should merged this in and continue the other dependency issues on another PR

**Pull request merged**
